name: salon_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  email_auth: ^1.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.0.15
  intl: ^0.18.1
  rive: ^0.12.1
  url_launcher: ^6.1.3
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  
flutter:

  uses-material-design: true

  assets:
    - images/
    - rive/
  
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
